apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-routing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - pathType: Prefix      
        backend:
          service:
            name: k8s-hello-svc
            port:
              number: 80
        path: /hello
      - pathType: Prefix      
        backend:
          service:
            name: nginx-svc
            port:
              number: 80
        path: /nginx
      - pathType: Prefix      
        backend:
          service:
            name: nodejs-feedback-svc
            port:
              number: 80
        path: /nodejsfeed

